//SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;
pragma abicoder v2;

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.8/interfaces/KeeperCompatibleInterface.sol";

error StakeMonitor__UpkeepNotNeeded();
error StakeMonitor__TransferFailed();
error StakingMonitor__UpperBond_SmallerThan_LowerBound();
error StakeMonitor__UserHasntDepositedETH();

struct userInfo {
    uint256 balance;
    uint256 tokenSymbol;
    uint256 priceLimit;
}

contract StakingMonitor is KeeperCompatibleInterface {
    mapping(address => userInfo) public s_userInfos;
    address[] s_addresses;
    event Deposited(address indexed user);
    AggregatorV3Interface public priceFeed;

    uint256 public s_lowestPriceLimit;

    constructor(address _priceFeed) {
        priceFeed = AggregatorV3Interface(_priceFeed);
    }

    function getPrice() public view returns (uint256) {
        (, int256 answer, , , ) = priceFeed.latestRoundData();
        return uint256(answer);
    }

    function deposit() external payable {
        s_userInfos[msg.sender].balance =
            s_userInfos[msg.sender].balance +
            msg.value;
        s_addresses.push(msg.sender);
        emit Deposited(msg.sender);
    }

    function setPriceLimit(uint256 _priceLimit) external {
        // a user cannot set a price limit if they haven't deposited some eth
        if (s_userInfos[msg.sender].balance == 0) {
            revert StakeMonitor__UserHasntDepositedETH();
        }

        s_userInfos[msg.sender].priceLimit = _priceLimit;

        // set lowest price limit across all users, to trigger upkeep if the lowest price limit is reached
        if ((s_lowestPriceLimit == 0) || (s_lowestPriceLimit > _priceLimit)) {
            s_lowestPriceLimit = _priceLimit;
        }
    }

    function calculatePriceRange() public view returns (bool) {
        uint price = getPrice();
        bool upkeepNeeded = (price > s_lowestPriceLimit);
        return upkeepNeeded;
    }

    function checkUpkeep(bytes calldata checkData)
        external
        override
        returns (bool upkeepNeeded, bytes memory performData)
    {
        upkeepNeeded = calculatePriceRange();

        // We don't use the checkData in this example
        // checkData was defined when the Upkeep was registered
        performData = checkData;
    }

    function performUpkeep(bytes calldata performData) external override {
        // iterate over users price limits
        // trigger the sale if current ether price is above price limit for user

        // We don't use the performData in this example
        // performData is generated by the Keeper's call to your `checkUpkeep` function
        performData;
    }
}
